"""empty message

Revision ID: 0264042c5696
Revises: 51100db21448
Create Date: 2024-08-31 00:59:46.765115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0264042c5696'
down_revision: Union[str, None] = '51100db21448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('date_publish', sa.DateTime(), nullable=True))
    op.add_column('announcements', sa.Column('count_views', sa.Integer(), nullable=True))
    op.add_column('announcements', sa.Column('title', sa.String(), nullable=False))
    op.add_column('announcements', sa.Column('main_photo', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('description', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('attachments', sa.String(), nullable=True))
    op.add_column('announcements', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'price')
    op.drop_column('announcements', 'attachments')
    op.drop_column('announcements', 'description')
    op.drop_column('announcements', 'main_photo')
    op.drop_column('announcements', 'title')
    op.drop_column('announcements', 'count_views')
    op.drop_column('announcements', 'date_publish')
    # ### end Alembic commands ###
